---
openapi: 3.1.0
components:
  schemas:
    Date:
      type: string
      format: date
      examples:
      - 2022-03-10
    MonetaryAmountSchema:
      properties:
        amount:
          type: number
        currency:
          type: string
      type: object
    UseNativeType:
      $ref: "#/components/schemas/Date"
      type: object
      properties:
        value:
          $ref: "#/components/schemas/Date"
        internalValue:
          type: string
        composite:
          type: boolean
        "null":
          type: boolean
    UseSchemaImplementationImpl:
      type: object
      properties:
        amount:
          type: number
        currency:
          type: string
    UseSchemaImplementationType:
      $ref: "#/components/schemas/UseSchemaImplementationImpl"
      type: object
      properties:
        value:
          type: string
        internalValue:
          type: string
        composite:
          type: boolean
        "null":
          type: boolean
    UseSchemaRefType:
      $ref: "#/components/schemas/MonetaryAmountSchema"
      type: object
      properties:
        value:
          type: string
        internalValue:
          type: string
        composite:
          type: boolean
        "null":
          type: boolean
paths:
  /schema/UseNativeType:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UseNativeType"
        required: true
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
      summary: Use Native Type
      tags:
      - Greeting Resource
  /schema/UseSchemaImplementationType:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UseSchemaImplementationType"
        required: true
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
      summary: Use Schema Implementation Type
      tags:
      - Greeting Resource
  /schema/UseSchemaRefType:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UseSchemaRefType"
        required: true
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
      summary: Use Schema Ref Type
      tags:
      - Greeting Resource
info:
  title: openapi-schema-problems API
  version: 1.0.0-SNAPSHOT
servers:
- url: http://localhost:8080
  description: Auto generated value
- url: http://0.0.0.0:8080
  description: Auto generated value
